services:
  app:
    env_file: ../.env
    image: pwd-image
    container_name: pwd
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    pull_policy: build
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${APP_PATH}/src:/app/src
      - ${APP_PATH}/main.py:/app/main.py
      - ${PWD_DATABASE_PATH}:${PWD_DATABASE_PATH}
    network_mode: host
    command: uv run python main.py
